---
- name: "p0"
  
  stream:
    action_count: 0
    enabled: true
    flags: 2
    flow_stats:
      enabled: true
      rule_type: "stats"
      stream_id: 0
    isg: 0.0
    mode:
      rate:
        type: "percentage"
        value: 9.0
      type: "continuous"
      total_pkts: 1
      pkts_per_burst: 1
      ibg: 0.0
      count: 1
    
    packet:
      binary: "AAEAAAABAgAAAAAACABFAAAuBNIAAH8AZUgYAAAAEAAAAAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBka"
      meta: "eyJwcm90b2NvbF9zZWxlY3Rpb24iOnsiZnJhbWVfbGVuZ3RoIjoiNjQiLCJpc190Y3Bfc2VsZWN0ZWQiOmZhbHNlLCJpc19pcHY0X3NlbGVjdGVkIjp0cnVlLCJtYXhfbGVuZ3RoIjoiMTUxOCIsImlzX3VkcF9zZWxlY3RlZCI6ZmFsc2UsIm1pbl9sZW5ndGgiOiI2NCIsImZyYW1lX2xlbmd0aF90eXBlIjoiRml4ZWQiLCJpc190YWdnZWRfdmxhbl9zZWxlY3RlZCI6ZmFsc2UsImlzX3BhdHRlcm5fc2VsZWN0ZWQiOnRydWV9LCJldGhlcm5ldCI6eyJ0eXBlIjoiMDgwMCIsImlzX292ZXJyaWRlIjp0cnVlfSwibWFjIjp7InNvdXJjZSI6eyJhZGRyZXNzIjoiMDI6MDA6MDA6MDA6MDA6MDAiLCJjb3VudCI6IjkwMDAiLCJzdGVwIjoiMSIsIm1vZGUiOiJUUmV4IENvbmZpZyJ9LCJkZXN0aW5hdGlvbiI6eyJhZGRyZXNzIjoiMDA6MDE6MDA6MDA6MDA6MDEiLCJjb3VudCI6IjkwMDAiLCJzdGVwIjoiMSIsIm1vZGUiOiJGaXhlZCJ9fSwiaXB2NCI6eyJzb3VyY2UiOnsiYWRkcmVzcyI6IjI0LjAuMC4wIiwiY291bnQiOiI1MDAwMDAiLCJzdGVwIjoiMSIsIm1vZGUiOiJJbmNyZW1lbnQgSG9zdCJ9LCJkZXN0aW5hdGlvbiI6eyJhZGRyZXNzIjoiMTYuMC4wLjAiLCJjb3VudCI6IjUwMDAwMCIsInN0ZXAiOiIxIiwibW9kZSI6IkluY3JlbWVudCBIb3N0In19LCJ0Y3AiOnsiaXNfb3ZlcnJpZGVfZHN0X3BvcnQiOmZhbHNlLCJjaGVja3N1bSI6IkIzRTMiLCJ1cmdlbnRfcG9pbnRlciI6IjAiLCJpc191cmciOmZhbHNlLCJpc19hY2siOmZhbHNlLCJpc19wc2giOmZhbHNlLCJpc19yc3QiOmZhbHNlLCJpc19zeW5jIjpmYWxzZSwiaXNfZmluIjpmYWxzZSwiYWNrX251bWJlciI6IjAiLCJ3aW5kb3ciOiIxMDI0IiwiaXNfb3ZlcnJpZGVfc3JjX3BvcnQiOmZhbHNlLCJpc19vdmVycmlkZV9jaGVja3N1bSI6ZmFsc2UsInNlcXVlbmNlX251bWJlciI6IjEyOTAxOCIsInNyY19wb3J0IjoiMTAyNSIsImRzdF9wb3J0IjoiMTAyNSJ9LCJ1ZHAiOnsiaXNfb3ZlcnJpZGVfZHN0X3BvcnQiOmZhbHNlLCJsZW5ndGgiOiIyNiIsImNoZWNrc3VtIjoiRkZCQSIsImlzX292ZXJyaWRlX2xlbmd0aCI6ZmFsc2UsImlzX292ZXJyaWRlX3NyY19wb3J0IjpmYWxzZSwiaXNfb3ZlcnJpZGVfY2hlY2tzdW0iOmZhbHNlLCJzcmNfcG9ydCI6IjEwMjUiLCJkc3RfcG9ydCI6IjEwMjUifSwicGF5bG9hZCI6eyJ0eXBlIjoiSW5jcmVtZW50IEJ5dGUiLCJwYXR0ZXJuIjoiMDAifSwidmxhbiI6eyJwcmlvcml0eSI6IjAiLCJpc19vdmVycmlkZV90cF9pZCI6ZmFsc2UsImNmaSI6IjAiLCJ2X2lkIjoiMCIsInRwX2lkIjoiRkZGRiJ9LCJhZHZhbnNlZF9wcm9wZXJ0aWVzIjp7ImNhY2hlX3NpemVfdHlwZSI6IkF1dG8iLCJjYWNoZV92YWx1ZSI6IjUwMDAifSwibW9kZWxfdmVyc2lvbiI6IjEuMCJ9"
      model: ""
    self_start: true
    start_paused: false
    advanced_mode: false
    vm:
      split_by_var: "ip_src"
      instructions:
      - init_value: 268435456
        min_value: 268435456
        max_value: 268935455
        name: "ip_dest"
        op: "inc"
        size: 4
        step: 1
        type: "flow_var"
      - add_value: 0
        is_big_endian: true
        name: "ip_dest"
        pkt_offset: 30
        type: "write_flow_var"
      - init_value: 402653184
        min_value: 402653184
        max_value: 403153183
        name: "ip_src"
        op: "inc"
        size: 4
        step: 1
        type: "flow_var"
      - add_value: 0
        is_big_endian: true
        name: "ip_src"
        pkt_offset: 26
        type: "write_flow_var"
      - pkt_offset: 14
        type: "fix_checksum_ipv4"
      cache_size: 5000
  stream_id: 0
